### ISSUE TITLE
FreeBSD 12 compile error for sigar. 

### ISSUE THREAD

**Issue by emanzx** [kostya/sigar#6]
I have look around in FreeBSD pkg for sigar and found they did improved it for the latest freeBSD 12.
here are the patch 
https://svnweb.freebsd.org/ports/head/devel/sigar/files/patch-src_os_darwin_darwin__sigar.c?view=markup&pathrev=438996

for more info on freeBSD sigar port. you can get it here. 
https://www.freshports.org/devel/sigar/

Im not good in C lang. sorry.

**Comment by kostya** [comment]
i applied that patch, and push gem `2.0.6.test`, can you test it `gem install kostya-sigar --pre`?

**Comment by emanzx** [comment]
Perfecto~
![image](https://user-images.githubusercontent.com/2576990/51370442-179d2480-1b32-11e9-943a-33a1cb94b5b5.png)
Thanks..

**Comment by emanzx** [comment]
I have tested with latest eye.. seem working.. can close this issue.. and I hope can update eye to use this updated gem..
